services:
  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: summarease-backend
    ports:
      - "5000:7860"  # Local port 5000 maps to container port 7860 (Hugging Face standard)
    env_file:
      - backend/.env
    environment:
      - FLASK_ENV=development
      - PORT=7860
    volumes:
      - ./backend:/app/backend
      - ./ml_models:/app/ml_models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - summarease-network

  # Frontend Streamlit Service  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: summarease-frontend
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - BACKEND_URL=${BACKEND_URL:-http://backend:5000}
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - summarease-network

networks:
  summarease-network:
    driver: bridge

volumes:
  model-data:
    driver: local 